### ISSUE TITLE
Error in eval(predvars, data, env): object 'FEATURE_NAME' not found

### ISSUE THREAD

**Issue by charlie9526** [susanne-207/moc#6]
Error in eval(predvars, data, env): object 'FEATURE_NAME' not found
Here FEATURE_NAME is a onehot encoded column name.
ex - if categorical column name is "columnA"  , "value1" is the value. Then the  FEATURE_NAME is "coulmnAvalue1"

my problem is this was happen only for "classif.randomForest", but "classif.xgboost" works without this error. And also when I tried  randomForest regressor in seperate project with proper preprocess steps. That also works. 

What is the problem? Is this library is not compatible with "classif.randomForest" ?

**Comment by dandls** [comment]
Can you please provide a reproducible example? 
When I change classif.xgboost to classif.randomForest in my posted example on the pima dataset, it works fine. 
```
devtools::load_all("../iml", export_all = FALSE)
devtools::load_all("../counterfactuals", export_all = FALSE)

set.seed(111)
library("mlr")
library("mlrCPO")
library("ggplot2")

###---- Tune & train model ----
task = mlr::pid.task
df = getTaskData(pid.task)
lrn = makeLearner("classif.randomForest", predict.type = "prob")
lrn = cpoDummyEncode() %>>% cpoScaleRange() %>>%  lrn
model = mlr::train(lrn, task) 

###--- Define a predictor as input for the counterfactual method ----
pred = Predictor$new(model = model, data = df, class = "neg",
  conditional = FALSE)
ctr = partykit::ctree_control(maxdepth = 5L)

###---- Compute counterfactuals ----
x.interest = df[1,]
pred$predict(x.interest)

cf = Counterfactuals$new(predictor = pred, 
  x.interest = x.interest, 
  target = c(0.5, 1), epsilon = 0, generations = 20)
```

**Comment by charlie9526** [comment]
Thank you for reply! I will check this!
